### ISSUE TITLE
[BUG] Nested objects wrap/unwrap issue

### ISSUE THREAD

**Issue by cdengxepam** [zhengxin-wang/line-breaker#2]
Hi @zhengxin-wang 

Here's the reproduce steps:

Step1: select a nested object, then tap **ALT + CTRL + L**
![image](https://github.com/zhengxin-wang/line-breaker/assets/142557369/a87e5130-1b7d-4b8b-bb94-d98d49f9f7a7)

Step2: tailing brackets seem at wrong places
![image](https://github.com/zhengxin-wang/line-breaker/assets/142557369/3c5781a8-ae5f-4877-bdc8-2753792f1087)

**Comment by zhengxin-wang** [comment]
Hi @cdengxepam thanks for the feedback, issue is fixed in commit [3d3fcb5](https://github.com/zhengxin-wang/line-breaker/commit/3d3fcb5c105a0d7ded8958115fd51d09d6f70a39)
The way of processing the string has been simplified: from regex to standard string trimming. 
I also find there is some issue with switching it back, will fix it and release them together with issue #1 and #2 at the VS Code extension market.

Best Regards!
